### ISSUE TITLE
Error in configuring pb

### ISSUE THREAD

**Issue by jdebacker** [open-source-economics/policybrain-builder#68]
I'm having trouble getting past the [Configuration](https://github.com/open-source-economics/policybrain-builder#configuration) step.

when I do `conda install anaconda-client` I get the following:

```
Fetching package metadata .....
CondaHTTPError: HTTP 401 UNAUTHORIZED for url <https://conda.anaconda.org/t/<token>/opensourcepolicycenter/osx-64/repodata.json>
Elapsed: 00:00.030698
CF-RAY: 39b42e952ad056f3-IAD

The token '<token>' given for the URL is invalid.

If this token was pulled from anaconda-client, you will need to use
anaconda-client to reauthenticate.

If you supplied this token to conda directly, you will need to adjust your
conda configuration to proceed.

Use `conda config --show` to view your configuration's current state.
Further configuration help can be found at <https://conda.io/docs/config.html>.
```

`cona config --show` returns:

```
A02655JDEBACKER:policybrain-builder jason.debacker$ conda config --show
add_anaconda_token: True
add_pip_as_python_dependency: True
allow_non_channel_urls: True
allow_softlinks: True
always_copy: False
always_softlink: False
always_yes: True
anaconda_upload: None
auto_update_conda: True
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: True
channels:
  - anaconda-fusion
  - https://conda.anaconda.org/t/<token>/opensourcepolicycenter
  - https://conda.anaconda.org/t/<token BUT WITH FIRST CHARACTER CHANGED>/opensourcepolicycenter
  - defaults
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
create_default_packages: []
custom_channels:
  pkgs/free: https://repo.continuum.io/
  pkgs/r: https://repo.continuum.io/
  pkgs/pro: https://repo.continuum.io/
custom_multichannels:
  defaults: ["https://repo.continuum.io/pkgs/free", "https://repo.continuum.io/pkgs/r", "https://repo.continuum.io/pkgs/pro"]
  local: []
default_channels:
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/r
  - https://repo.continuum.io/pkgs/pro
disallow: []
envs_dirs:
  - /Users/jason.debacker/anaconda/envs
  - /Users/jason.debacker/.conda/envs
force: False
json: False
local_repodata_ttl: 1
migrated_channel_aliases: []
offline: False
path_conflict: clobber
pinned_packages: []
pkgs_dirs:
  - /Users/jason.debacker/anaconda/pkgs
  - /Users/jason.debacker/.conda/pkgs
proxy_servers: {}
quiet: False
remote_connect_timeout_secs: 9.15
remote_max_retries: 3
remote_read_timeout_secs: 60.0
rollback_enabled: True
shortcuts: True
show_channel_urls: None
ssl_verify: True
track_features: []
use_pip: True
verbosity: 0
```

But I don't know how to make sense of this.  Could the issue be related to there being to urls under "channels" with one of them having an incorrect string for the token?  If so, how would I change that

If I proceed to the `pb build` command, I get an error that suggests I need to set the configuration.

Please let me know if you have suggestions.  Thanks!

cc @martinholmer
